name = "doh-forward-worker"
main = "src/index.ts"
compatibility_date = "2025-11-05"
workers_dev = false

[vars]
UPSTREAM_ENDPOINT = "https://cloudflare-dns.com/dns-query"

[observability]
enabled = false
